// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxTXNh4bcuQ9NN9SCxo2x_oRsqAaYHSOk',
    appId: '1:1049992622811:web:33d7d3433e15ec1492d2fe',
    messagingSenderId: '1049992622811',
    projectId: 'fir-blog-28656',
    authDomain: 'fir-blog-28656.firebaseapp.com',
    storageBucket: 'fir-blog-28656.appspot.com',
    measurementId: 'G-0YJD397H3R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhATxwlLyyV0QdeWa87IGc6s7d7V939AU',
    appId: '1:1049992622811:android:5dec3e6e769f400492d2fe',
    messagingSenderId: '1049992622811',
    projectId: 'fir-blog-28656',
    storageBucket: 'fir-blog-28656.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALu6slFbjpjhZAPHcyVhnXtUyxOr7lE3U',
    appId: '1:1049992622811:ios:d8a5d864bb6e832692d2fe',
    messagingSenderId: '1049992622811',
    projectId: 'fir-blog-28656',
    storageBucket: 'fir-blog-28656.appspot.com',
    iosBundleId: 'com.example.ilkelblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALu6slFbjpjhZAPHcyVhnXtUyxOr7lE3U',
    appId: '1:1049992622811:ios:1890ff0145121b3092d2fe',
    messagingSenderId: '1049992622811',
    projectId: 'fir-blog-28656',
    storageBucket: 'fir-blog-28656.appspot.com',
    iosBundleId: 'com.example.ilkelblog.RunnerTests',
  );
}
